import Head from 'next/head';
import Link from 'next/link';
import { Box } from '@mui/system';
import TopBar from '@/components/global/Topbar';
import Dashboard from './dashboard';

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Dashboard />
      </Box>
    </Box>
  );
}
